# templates/jenkins.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    app: jenkins
spec:
  type: {{ .Values.jenkins.serviceType }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: {{ .Values.jenkins.image }}:{{ .Values.jenkins.tag }}
          imagePullPolicy: {{ .Values.jenkins.imagePullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
      volumes:
        - name: jenkins-home
          emptyDir: {}

